#ifndef VERSION_H
#define VERSION_H

#define EV_RCLONE_VERSION_MAJOR 1
#define EV_RCLONE_VERSION_MINOR 0
#define EV_RCLONE_VERSION_PATCH 0
#define EV_RCLONE_VERSION_BUILD 1

#define EV_RCLONE_VERSION_STRING "1.0.0.1"

#endif
